name: 'Setup MSYS2'
description: 'Setup an MSYS2 environment'
branding:
  color: purple
  icon: terminal
inputs:
  msystem:
    description: 'Variant of the environment to set by default: MSYS, MINGW32, MINGW64, UCRT64, CLANG64 or CLANGARM64'
    required: false
    default: 'MINGW64'
  path-type:
    description: 'Default value for MSYS2_PATH_TYPE environment variable: strict, inherit or minimal'
    required: false
    default: 'minimal'
  update:
    description: 'Update MSYS2 installation through pacman'
    required: false
    default: false
  install:
    description: 'After installation and/or update, install additional packages through pacman'
    required: false
    default: false
  pacboy:
    description: 'After installation and/or update, install additional packages through pacboy'
    required: false
    default: false
  installer-version:
    description: 'MSYS2 installer version (e.g. v1.12.2a)'
    required: false
    default: 'v1.12.2a'
  installer-checksum:
    description: 'SHA256 checksum of the installer EXE'
    required: false
    default: '7c454549122a6fcae54aabdb68080ce48b0144b27ce879c665d37d763b568e69'
  scala-version:
    description: 'Scala version (e.g. 2.12)'
    required: false
    default: '2.12'
  spinal-version:
    description: 'SpinalHDL version (e.g. 1.12.2)'
    required: false
    default: '1.12.2'
  release:
    description: 'Retrieve and extract base installation from upstream GitHub Releases'
    required: false
    default: true
  location:
    description: 'Where to install MSYS2'
    required: false
    default: 'RUNNER_TEMP'
  platform-check-severity:
    description: 'What to do when run on an incompatible runner: fatal, warn'
    required: false
    default: 'fatal'
  cache:
    description: 'If caching should be used'
    required: false
    default: true
outputs:
  msys2-location:
    description: 'The absolute path of the MSYS2 installation location'
runs:
  using: 'node20'
  main: 'index.js'
